# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Prog2\Qt_Exercise\liste_etude.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FenetreListView(object):
    def setupUi(self, FenetreListView):
        FenetreListView.setObjectName("FenetreListView")
        FenetreListView.resize(440, 333)
        self.View_etudiants = QtWidgets.QListView(FenetreListView)
        self.View_etudiants.setGeometry(QtCore.QRect(70, 20, 301, 231))
        self.View_etudiants.setObjectName("View_etudiants")
        self.Button_quitter = QtWidgets.QPushButton(FenetreListView)
        self.Button_quitter.setGeometry(QtCore.QRect(140, 270, 141, 41))
        self.Button_quitter.setObjectName("Button_quitter")

        self.retranslateUi(FenetreListView)
        QtCore.QMetaObject.connectSlotsByName(FenetreListView)

    def retranslateUi(self, FenetreListView):
        _translate = QtCore.QCoreApplication.translate
        FenetreListView.setWindowTitle(_translate("FenetreListView", "Liste d\'étudiant.e.s"))
        self.Button_quitter.setText(_translate("FenetreListView", "Quitter"))
